const {v4: uuidv4} = require('uuid');

/**
 * Task model
 * This class is used in order to create a new task instance in db
 */
class Task {
  /**
   * Class constructor
   * @param {object} params
   * @param {string} id? - id of a new task generated by UUID
   * @param {string} title - title of a new task
   * @param {number | null} order - number of order
   * @param {string | null} description - task description
   * @param {string | null} userId - uuid of user
   * @param {string} boardId - uuid of a board where task is located
   * @param {string} columnId - uuid of a column where task is located
   */
  constructor({
    id = uuidv4(),
    title,
    order,
    description,
    userId,
    boardId,
    columnId,
  } = {}) {
    this.id = id;
    this.order = order;
    this.title = title;
    this.description = description;
    this.boardId = boardId;
    this.columnId = columnId;
    this.userId = userId;
  }

  /**
   * Static method returns Task as a response to request
   * @param {Task} task
   * @returns {Task}
   */
  static toResponse(task) {
    return task;
  }
}

module.exports = Task;
