const {v4: uuidv4} = require('uuid');

/**
 * User model
 * This class is used in order to create a new user instance in db
 */
class User {
  /**
   * Class constructor
   * @param {object} params
   * @param {string} name - name of a user
   * @param {string} login - login of a user
   * @param {string} password - user password
   * @param {string} id - user id, be default generated by UUID
   */
  constructor({
    name = 'USER',
    login = 'user',
    password = 'P@55w0rd',
    id = uuidv4()
  } = {}) {
    this.id = id;
    this.name = name;
    this.login = login;
    this.password = password;
  }

  /**
   * Static method returns id, name, login as a response to request
   * @param {User} user - object with user from db
   * @returns {{name, id, login}}
   */
  static toResponse(user) {
    const { id, name, login } = user;
    return { id, name, login };
  }
}

module.exports = User;
