const {v4: uuidv4} = require('uuid');
const Column = require('./column.model');

/**
 * Board model
 * This class is used in order to create a new board instance in db
 */
class Board {
  /**
   * Class constructor
   * @param {object} params
   * @param {string} id - id generated by UUID
   * @param {string} title - title of board
   * @param {Array<Column>} columns -array of columns
   */
  constructor({
    id = uuidv4(),
    title = 'board',
    columns = [new Column()]
  } = {}) {
    this.id = id;
    this.title = title;
    this.columns = columns;
  }
  /**
   * Static method returns id, title, array of columns as a response to request
   * @param {Board} board
   * @returns {Board}
   */

  static toResponse(board) {
    return board;
  }
}

module.exports = Board;
